name: ⭐ Star Reminder on Issues and PRs

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  post-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Post star reminder comment
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.issue?.number || context.payload.pull_request?.number;

            const commentBody = `## 🌟 Thanks for contributing!

            Hey there! Thanks for opening this Issue/PR on the 
            [Advanced-Discord-Bot](https://github.com/harshendram/Advanced-Discord-Bot) project!

            If you found this project helpful, please consider giving it a ⭐:

            👉 [Click here to star the repo](https://github.com/harshendram/Advanced-Discord-Bot)

            Your support means a lot to us! 💖`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: commentBody
            });
