name: ⭐ Star Reminder on Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  post-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Get issue number
        id: vars
        run: echo "TARGET_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT

      - name: Comment on Issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.vars.outputs.TARGET_NUMBER }}
          body: |
            ---
            ## ✨ Thank You for Contributing!

            👋 Hey @${{ github.actor }}, thanks for opening this issue in the [**Advanced-Discord-Bot**](https://github.com/harshendram/Advanced-Discord-Bot) repository.

            > Your contribution helps us grow and improve this project 💪

            ---
            🌟 **Love this project? Show your support:**
            👉 [Give us a ⭐ on GitHub](https://github.com/harshendram/Advanced-Discord-Bot)

            _We appreciate your help and interest in making this better!_

            — The Maintainers 💖
